export {
  COMMON_PASSWORDS,
  DEFAULT_PASSWORD_CONFIG,
  KEYBOARD_PATTERNS,
  calculateEntropy,
  calculateScore,
  containsUserInput,
  estimateCrackTime,
  estimatePasswordStrength,
  generateFeedback,
  getCharsetSize,
  getStrengthLabel,
  hasKeyboardPattern,
  hasRepeatedChars,
  hasRepeatedPattern,
  hasSequentialChars,
  isCommonPassword,
  validatePassword,
  validatePasswordBasic,
  type BasicPasswordValidationResult,
  type PasswordConfig,
  type PasswordFeedback,
  type PasswordPenalties,
  type PasswordScore,
  type PasswordValidationResult,
  type StrengthResult,
} from "./password.js";
export {
  evaluateAccountLockout,
  isLockoutThresholdReached,
  progressiveDelayMs,
  type AccountLockoutDecision,
  type AccountLockoutFacts,
  type AccountLockoutPolicy,
} from "./lockout.js";
export {
  classifyRefreshCredential,
  credentialEpochMatches,
  deriveSessionSpanMs,
  evaluateSessionBinding,
  isActiveRefreshCredential,
  isRefreshRetryEligible,
  isSessionActive,
  isSessionIdle,
  isSessionRevoked,
  selectSessionsForEviction,
  sessionAgeMs,
  sessionIdleRemainingMs,
  sessionIdleWindowMs,
  sessionSpanMs,
  type RefreshCredentialDecision,
  type RefreshCredentialFacts,
  type SessionBindingDecision,
  type SessionLifetimePolicy,
} from "./session.js";
export {
  RbacPolicy,
  type AuthorizationDecision,
  type RoleDefinition,
} from "./authorization.js";
export {
  ExpiringReplayGuard,
  type ExpiringReplayGuardOptions,
} from "./challenge.js";
export {
  AUTH_AUDIT_EVENT_TYPES,
  createAuthAuditEvent,
  isSensitiveAuthAuditMetadataKey,
  type AuthAuditEvent,
  type AuthAuditEventType,
  type AuthAuditFactor,
  type AuthAuditMetadata,
  type AuthAuditMetadataValue,
  type AuthAuditOutcome,
  type AuthAuditSeverity,
  type CreateAuthAuditEventInput,
} from "./audit.js";
export {
  evaluateOneTimeCredential,
  type OneTimeCredentialDecision,
  type OneTimeCredentialFacts,
  type OneTimeCredentialPolicy,
  type OneTimeCredentialRejectionReason,
} from "./one-time-credential.js";
export type {
  AuthAuditPort,
  AuthNotification,
  AuthNotificationPort,
  AuthTransactionPort,
  OAuthIdentity,
  OAuthProviderPort,
  WebAuthnCredentialPort,
  WebAuthnCredentialRecord,
} from "./ports.js";
